openapi: 3.0.3
info:
  title: News Service API
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    NewsDto:
      properties:
        id:
          format: uuid
          type: string
        title:
          type: string
        text:
          type: string
        createdAt:
          format: date-time
          type: string
      type: object
    NewsCreateRequest:
      properties:
        title:
          maxLength: 255
          minLength: 3
          type: string
        text:
          minLength: 10
          type: string
      type: object
    CommentDto:
      properties:
        id:
          format: uuid
          type: string
        text:
          type: string
        username:
          type: string
        createdAt:
          format: date-time
          type: string
      type: object
    NewsWithCommentsDto:
      properties:
        id:
          format: uuid
          type: string
        title:
          type: string
        text:
          type: string
        createdAt:
          format: date-time
          type: string
        comments:
          items:
            $ref: "#/components/schemas/CommentDto"
          type: array
      type: object
    UserDetailsDto:
      properties:
        username:
          type: string
        authorities:
          items:
            type: string
          type: array
      required:
      - authorities
      - username
      type: object

