spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/NEWS_PLATFORM
    username: news_user
    password: news_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
