tasks.named('bootJar') {
    enabled = false
}

dependencies {
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.6")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.12.6")

    implementation 'org.mapstruct:mapstruct:1.4.2.Final'
    implementation("org.springframework.boot:spring-boot-starter-data-redis:3.4.1")
    implementation("jakarta.validation:jakarta.validation-api:3.1.0")
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation("org.springframework.security:spring-security-web:6.4.2")
    implementation("io.jsonwebtoken:jjwt-api:0.12.6")

}

test {
    useJUnitPlatform()
}

openApiGenerate {
    generatorName = "java"
    inputSpec = "${projectDir}/src/main/resources/openapi.yaml"
    outputDir = "${projectDir}/src/main/generated/openapi"
    apiPackage = "ru.clevertec.api"
    modelPackage = "ru.clevertec.dto"
    invokerPackage = "ru.clevertec.invoker"
    additionalProperties = [
            useLombok: 'true'
    ]
    configOptions = [
            dateLibrary                   : "custom",
            openApiNullable               : "false",
            interfaceOnly                 : "true",
            additionalModelTypeAnnotations: '@lombok.Data @lombok.AllArgsConstructor @lombok.Builder',
            useJakartaEe                  : 'true'
    ]
    generateApiDocumentation = false
    generateApiTests = false
    generateModelTests = false
    typeMappings = [
            "Date": "java.time.LocalDateTime"
    ]
    importMappings = [
            "LocalDateTime": "java.time.LocalDateTime"
    ]
}

sourceSets {
    main {
        java {
            srcDirs += "${projectDir}/src/main/generated/openapi"
        }
    }
}

tasks.named('compileJava') {
    dependsOn tasks.openApiGenerate
}
